### ISSUE TITLE
DRAM power consumption formula problems

### ISSUE THREAD

**Issue by hrexha28** [powerapi-ng/rapl-formula#18]
Hi,
I was using the option in the rapl-formula for measuring the dram consumption. But after running the senor, I try to start the docker for rapl-formula I get the error:
Traceback (most recent call last):                                                                                                                                                            File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                                                                    return _run_code(code, main_globals, None,                                      
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code                                                                                          
    exec(code, run_globals)                                                                   
  File "/opt/powerapi/.local/lib/python3.8/site-packages/rapl_formula/__main__.py", line 257, in <module>
    run_rapl(conf)                                                                            
  File "/opt/powerapi/.local/lib/python3.8/site-packages/rapl_formula/__main__.py", line 181, in run_rapl
    supervisor.launch(puller_cls, puller_start_message)                                                                                                                                     
  File "/opt/powerapi/.local/lib/python3.8/site-packages/powerapi/supervisor.py", line 128, in launch
    answer = self.system.ask(address, start_message)                                                                                                                                          File "/opt/powerapi/.local/lib/python3.8/site-packages/thespian/actors.py", line 736, in ask                                                                                              
    return self._systemBase.ask(actorAddr, msg, timeout)                                                                                                                                    
  File "/opt/powerapi/.local/lib/python3.8/site-packages/thespian/system/systemBase.py", line 261, in ask
    txwatch = self._tx_to_actor(anActor, msg)  # KWQ: pass timeout on tx??                                                                                                                  
  File "/opt/powerapi/.local/lib/python3.8/site-packages/thespian/system/systemBase.py", line 154, in _tx_to_actor
    self.transport.scheduleTransmit(                                                          
  File "/opt/powerapi/.local/lib/python3.8/site-packages/thespian/system/transport/asyncTransportBase.py", line 213, in scheduleTransmit
    transmitIntent.serMsg = self.serializer(transmitIntent)                                                                                                                                 
  File "/opt/powerapi/.local/lib/python3.8/site-packages/thespian/system/transport/MultiprocessQueueTransport.py", line 714, in serializer
    discard = pickle.dumps(wrappedMsg)                                                        
AttributeError: Can't pickle local object 'setup_dram_formula_actor.<locals>.<lambda>' 
If I can have some assistance?
Thank you.

**Comment by roda82** [comment]
Hello, 

The issue is corrected with the last push. However, it will be available on Docker Hub in the next release. 

Regards,

**Comment by hrexha28** [comment]
Hi,
Thanks for the update. Is there a way I can try the change without waiting for the docker image?
Regards.

**Comment by roda82** [comment]
Yes, you can clone the RAPL Formula repository and then build on your PC the Docker image by using the following command : 
 
sudo docker build -t powerapi/rapl-formula:latest <path_to_rapl_formula_repository>

Regards,

**Comment by roda82** [comment]
Hello, 
This problem was corrected with the V0.5.3 release. 

Regards,
